"""add last_name to users

Revision ID: 043c5d3fbe9f
Revises: c889fe1e3267
Create Date: 2026-05-24 12:17:48.959594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '043c5d3fbe9f'
down_revision: Union[str, Sequence[str], None] = 'c889fe1e3267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_column('users', 'second_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('second_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
